# Generated by Django 5.2.8 on 2025-11-27 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=200, verbose_name='Головний заголовок')),
                ('flag', models.ImageField(upload_to='flags/', verbose_name='Прапор')),
            ],
            options={
                'verbose_name': 'Країна',
                'verbose_name_plural': 'Країни',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSupplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок події ')),
                ('description', models.CharField(max_length=500, verbose_name='Опис події')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок періоду')),
                ('short_description', models.TextField(verbose_name='Короткий опис')),
                ('detail', models.TextField(blank=True, verbose_name='Повний текст статті')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Дизлайки')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='app.country', verbose_name='Країна')),
            ],
            options={
                'verbose_name': 'Історичний період',
                'verbose_name_plural': 'Історичні періоди',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPeriodDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000, verbose_name='Опис')),
                ('quote', models.CharField(max_length=100, verbose_name='Цитати')),
                ('historical_title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('source', models.CharField(max_length=100, verbose_name='Джерело інформації')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_details', to='app.historicalperiod', verbose_name='Період')),
                ('historical_context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.historicalsupplement', verbose_name='Перелік подій')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False, verbose_name='Це правильна відповідь?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.question')),
            ],
        ),
    ]
