# Generated by Django 5.2.8 on 2025-11-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperioddetail',
            name='historical_context',
        ),
        migrations.AddField(
            model_name='historicalperioddetail',
            name='historical_context',
            field=models.ManyToManyField(blank=True, related_name='details', to='app.historicalsupplement', verbose_name='Перелік подій'),
        ),
    ]
