# Generated by Django 5.2.8 on 2025-11-27 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_historicalperioddetail_historical_context_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.historicalperiod', verbose_name='Період'),
        ),
        migrations.RemoveField(
            model_name='historicalperioddetail',
            name='historical_context',
        ),
        migrations.AddField(
            model_name='historicalperioddetail',
            name='historical_context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='app.historicalsupplement', verbose_name='Перелік подій'),
        ),
    ]
