# Generated by Django 5.2.8 on 2025-11-27 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_question_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPeriodEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок періоду')),
                ('short_description', models.TextField(verbose_name='Короткий опис')),
                ('detail', models.TextField(blank=True, verbose_name='Повний текст статті')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Лайки')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Дизлайки')),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalperiod',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='historicalperiod',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='historicalperiod',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='historicalperiod',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='historicalperiod',
            name='title',
        ),
        migrations.AddField(
            model_name='historicalperiod',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.historicalperiodevents'),
        ),
    ]
