# Generated by Django 5.2.8 on 2025-11-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_historicalperiodevents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Unnamed')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
